In [0]:
import numpy as np

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2;  
произведение не определенно, так как в первой матрице 2 столбца, а во второй матрице 4 строки  
  
б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;  
произведение определенно, результирующая матрица будет 2 х 3  
  

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;  
произведение определенно, результирующая матрица будет 8 х 8  
  
г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .  
произведение определенно, результирующая матрица будет 4 х 4

2.  
Найти сумму и произведение матриц  A=$\begin{pmatrix}
1 & -2 \\
3 & 0
\end{pmatrix}$  и  B=$\begin{pmatrix}
4 & -1 \\
0 & 5
\end{pmatrix}$. 

A + B = $\begin{pmatrix}
5 & -3 \\
3 & 5
\end{pmatrix}$    
AB = $\begin{pmatrix}
4 & -11 \\
12 & -3
\end{pmatrix}$

In [106]:
#Проверка
a = np.array([[1,-2],[3,0]])
b = np.array([[4,-1],[0,5]])

a+b

array([[ 5, -3],
       [ 3,  5]])

In [107]:
np.dot(a,b)

array([[  4, -11],
       [ 12,  -3]])

3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3A−2B+4C  для матриц  A=$\begin{pmatrix}
1 & 7 \\
3 & -6
\end{pmatrix}$ ,  B=$\begin{pmatrix}
0 & 5 \\
2 & -1
\end{pmatrix}$, C=$\begin{pmatrix}
2 & -4 \\
1 & 1
\end{pmatrix}$

3A−2B+4C = $\begin{pmatrix}
3*1-2*0+4*2 & 3*7-2*5+4*(-4) \\
3*3-2*2+4*1 & -6*3-2*(-1)+4*1
\end{pmatrix}$ =$\begin{pmatrix}
11 & -5 \\
9 & -12
\end{pmatrix}$

In [108]:
#Проверка
a = np.array([[1,7],[3,-6]])
b = np.array([[0,5],[2,-1]])
c = np.array([[2,-4],[1,1]])

3*a - 2*b + 4*c


array([[ 11,  -5],
       [  9, -12]])

4. Дана матрица  A=$\begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix}$ . Вычислить  $AA^T$  и  $A^TA$ .

$AA^T$ = $\begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix}$ * $\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3 \\
\end{pmatrix}$ = $\begin{pmatrix}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}$  
$A^TA$ = $\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3 \\
\end{pmatrix}$*$\begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix}$ = $\begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}$

In [109]:
#Проверка
a = np.array([[4,1],[5,-2],[2,3]])

np.dot(a,a.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [110]:
np.dot(a.T,a)

array([[45,  0],
       [ 0, 14]])

5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [0]:
def dot(a,b):
  if len(a[0]) != len(b):
    print(f'Матрицы не возможно перемножить: в первой матрице столбцов: {len(a[0])}, во второй матрице строк: {len(b)}')
  
  #Генерируем результирующую матрицу нужного размера
  result = []
  for row in range(len(a)):
    row = []
    for i in range(len(b[0])):
      row.append(0)          
    result.append(row)

  for i,a_row in enumerate(a):    
    for b_column in range(len(b[0])): 
      x = 0     
      for j,a_number in enumerate(a_row):
        x += a_number*b[j][b_column]

      result[i][b_column] = x

  return result
        

In [112]:
a = [[1,-2],[3,0]]
b = [[4,-1], [0,5]]

dot(a,b)

[[4, -11], [12, -3]]

In [113]:
#Проверка
a = np.array([[1,-2],[3,0]])
b = np.array([[4,-1], [0,5]])

np.dot(a,b)

array([[  4, -11],
       [ 12,  -3]])